### ISSUE TITLE
"Error: connect ETIMEDOUT 192.168.1.80:9999"

### ISSUE THREAD

**Issue by thebaldgeek** [biddster/node-red-contrib-hs100#5]
Hi.
Thanks for this Node. Unfortunately, I have not been able to get it to work.
Here is the error from the log; (My HS100 is called 'blue light').

25 Feb 16:21:00 - [info] Started modified flows
HS100 Plug TCP error
Trace: { Error: connect ETIMEDOUT 192.168.1.80:9999
    at Object._errnoException (util.js:1024:11)
    at _exceptionWithHostPort (util.js:1046:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1182:14)
  code: 'ETIMEDOUT',
  errno: 'ETIMEDOUT',
  syscall: 'connect',
  address: '192.168.1.80',
  port: 9999 }
    at Socket.socket.on.on.on (C:\Users\beno\.node-red\node_modules\fx-hs100-api\lib\plug.js:62:17)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at emitErrorNT (internal/streams/destroy.js:64:8)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickDomainCallback (internal/process/next_tick.js:218:9)
25 Feb 16:21:25 - [error] [hs100:blue light] Error: connect ETIMEDOUT 192.168.1.80:9999

I'm running Node-RED v0.18.3 on Windows 10 Pro.

Have restarted Node-RED many time, removed and reinstalled your node.

Here is my example flow that fails;
[{"id":"eccaa64f.e988b8","type":"hs100","z":"7d8442cd.f9640c","name":"blue light","host":"192.168.1.80","x":810.5000114440918,"y":940.5000057220459,"wires":[[]]},{"id":"de9e4ee1.39a49","type":"inject","z":"7d8442cd.f9640c","name":"","topic":"on","payload":"","payloadType":"str","repeat":"","crontab":"","once":false,"onceDelay":0.1,"x":633.7500076293945,"y":978.7500057220459,"wires":[["eccaa64f.e988b8"]]},{"id":"d8a09109.f9f2f","type":"inject","z":"7d8442cd.f9640c","name":"","topic":"off","payload":"","payloadType":"str","repeat":"","crontab":"","once":false,"onceDelay":0.1,"x":628.7500076293945,"y":922.5000057220459,"wires":[["eccaa64f.e988b8"]]}]

I can use the HS100 both from the Android app and my Alexa device fine. Both ON/OFF commands from these apps work as expected.
I have rebooted the HS100 many times.

Not sure what to try next.

Thanks for your input.

**Comment by biddster** [comment]
I'm not sure, I don't actually own one. I wrote this blind for a friend. 

What version of nodejs are you using?

**Comment by elyobelyob** [comment]
Hi, I also get this. I have three nodes connecting to the same plug in the same flow.
<img width="339" alt="screenshot 2018-12-14 at 17 14 20" src="https://user-images.githubusercontent.com/298022/50017450-fd68a780-ffc3-11e8-8254-acca5cd7d4e1.png">
